# This rule is not used by the project orchestrator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the orchestration.operator.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: orchestrator
    app.kubernetes.io/managed-by: kustomize
  name: placementdecision-editor-role
rules:
- apiGroups:
  - orchestration.operator.io
  resources:
  - placementdecisions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - orchestration.operator.io
  resources:
  - placementdecisions/status
  verbs:
  - get
