---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - eventsources
  - sensors
  - workflowtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - orchestration.operator.io
  resources:
  - orchestrators
  - placementdecisions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - orchestration.operator.io
  resources:
  - orchestrators/finalizers
  - placementdecisions/finalizers
  verbs:
  - update
- apiGroups:
  - orchestration.operator.io
  resources:
  - orchestrators/status
  - placementdecisions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - policy.karmada.io
  resources:
  - overridepolicies
  - propagationpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
